name: Docker-thanqs

on:
  push:
    branches:
      - main
      - qa
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: rg.nl-ams.scw.cloud
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Get Next Version
        if: github.event_name != 'pull_request'
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: warn

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            rg.nl-ams.scw.cloud/thanqs/zitadel-login
          tags: |
            type=edge
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
            type=semver,pattern={{version}},value=${{steps.semver.outputs.next}}

      - name: Install dependencies
        run: pnpm install

      - name: Generate stubs
        run: pnpm generate

      - name: Build for Docker
        run: |
          pnpm build
          pnpm build:login:standalone

      - name: Build and Push Image
        id: build
        uses: docker/build-push-action@v5
        timeout-minutes: 10
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create tag
        if: ${{ steps.semver.outputs.next != '' }}
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.semver.outputs.next }}',
              sha: context.sha
            })
