name: Docker-thanqs

on:
  push:
    branches:
      - main
      - qa
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: rg.nl-ams.scw.cloud
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Get Next Version
        if: github.event_name != 'pull_request'
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noVersionBumpBehavior: warn

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            rg.nl-ams.scw.cloud/thanqs/zitadel-login
          tags: |
            type=sha
            type=semver,pattern={{version}},value=${{steps.semver.outputs.next}}

      - name: Build and Push Image
        id: build
        uses: docker/build-push-action@v5
        timeout-minutes: 10
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create tag
        if: ${{ steps.semver.outputs.next != '' }}
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.semver.outputs.next }}',
              sha: context.sha
            })
